name: "Tags"

on:
  release:
    types: [published]

jobs:
  tags:
    name: "Tags"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: "Update Tags"
        uses: cssnr/update-version-tags-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
